#!/bin/bash

# shopt -u expand_aliases

photo_directory=photos

function most_recent_photo {
    ls -tp "$photo_directory" | grep -v / | head -1
}

if [ $# -eq 0 ]
then
    photo=$(most_recent_photo)
else
    photo=$1
fi

if [ -z "$photo" ] || ! [ -f "$photo_directory/$photo" ]
then
    echo "specified photo ($photo) does not exist"
    exit 1
fi

echo "restart from $photo"
if ! cp "$photo_directory/$photo" restart_photo
then
    echo "failed to copy photo ($photo)"
    exit 1
fi

{
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
    ./star
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
} 2>&1 | tee output_restart.txt ;


# try to find last png
png=$(find  -path "./png/single*.png" -printf "%T@ %P\n" | sort -n | tail -1 | awk '{print $2}');
tail -n 50 output_restart.txt | mail -A $png -a "From:simulations@arizona.edu" -s "ua_w done" mrenzo@arizona.edu
