#!/bin/bash

{
    rm -f restart_photo

    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
    ./star
    date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
} 2>&1 | tee output.txt ; # save both stderr and stdout

# try to find last png
png=$(find  -path "./png/single*.png" -printf "%T@ %P\n" | sort -n | tail -1 | awk '{print $2}') ;
tail -n 50 output.txt | mail -A $png -a "From:simulations@arizona.edu" -s "MASS OMEGA_DIV_OMEGA_CRIT done" youremail
